import { useEffect, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { KpiCard, PageHeader } from "../components/analytics/DashboardComponents";
import { HISTORY_UPDATED_EVENT, HistoryRecord, clearHistory, getHistory } from "../services/history";

const toolLabels: Record<string, string> = { get_sales_summary: "Sales Summary", get_top_products: "Top Products", compare_sales_periods: "Sales Period Comparison", get_product_sales: "Product Sales", get_inventory_status: "Inventory Status", get_low_stock_products: "Low Stock Products", get_inventory_summary: "Inventory Summary", get_supplier_information: "Supplier Information", get_suppliers_summary: "Suppliers Summary", get_reorder_recommendations: "Reorder Recommendations" };
const duration = (ms: number) => ms >= 1000 ? `${(ms / 1000).toFixed(1)} s` : `${Math.round(ms)} ms`;

export function AutomationHistoryPage() {
  const [records, setRecords] = useState<HistoryRecord[]>(() => getHistory());
  const [filter, setFilter] = useState<"all" | "success" | "failed" | "tool">("all");
  const [search, setSearch] = useState("");
  const [confirming, setConfirming] = useState(false);
  useEffect(() => { const refresh = () => setRecords(getHistory()); window.addEventListener(HISTORY_UPDATED_EVENT, refresh); window.addEventListener("storage", refresh); return () => { window.removeEventListener(HISTORY_UPDATED_EVENT, refresh); window.removeEventListener("storage", refresh); }; }, []);
  const visible = useMemo(() => records.filter((record) => (filter === "all" || (filter === "tool" ? record.tool_calls.length > 0 : record.status === filter)) && (!search.trim() || record.request.toLowerCase().includes(search.toLowerCase()))), [records, filter, search]);
  const successes = records.filter((r) => r.status === "success");
  const toolCalls = records.reduce((sum, r) => sum + r.tool_calls.length, 0);
  const average = successes.length ? successes.reduce((sum, r) => sum + r.total_execution_time_ms, 0) / successes.length : 0;
  const performClear = () => { clearHistory(); setRecords([]); setConfirming(false); };

  return <section className="space-y-6"><PageHeader eyebrow="Local activity trace" title="Automation History" description="Review sanitized assistant interactions stored locally in this browser for portfolio and demonstration purposes." />
    <div className="rounded-xl border border-blue-200 bg-blue-50 px-5 py-4 text-sm leading-6 text-blue-900"><strong>Browser-local history only.</strong> Records are limited to the latest 25 interactions and are not synchronized, shared, or persisted by the backend.</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Total Interactions" value={String(records.length)} /><KpiCard label="Successful Requests" value={String(successes.length)} /><KpiCard label="Total Tool Calls" value={String(toolCalls)} /><KpiCard label="Average Response Time" value={duration(average)} /></div>
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-wrap gap-2" role="group" aria-label="History status filter">{(["all", "success", "failed", "tool"] as const).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} aria-pressed={filter === item} className={`rounded-md px-3 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-blue-200 ${filter === item ? "bg-slate-900 text-white" : "border border-slate-300 bg-white text-slate-600"}`}>{item === "tool" ? "Tool used" : item[0].toUpperCase() + item.slice(1)}</button>)}</div><div className="flex flex-col gap-3 sm:flex-row"><label className="text-xs font-semibold text-slate-600">Search requests<input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search request text" className="mt-1 block rounded-md border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-100" /></label>{records.length ? !confirming ? <button type="button" onClick={() => setConfirming(true)} className="self-end rounded-md border border-rose-300 bg-white px-4 py-2 text-sm font-semibold text-rose-700 focus:outline-none focus:ring-2 focus:ring-rose-200">Clear history</button> : <div className="flex items-end gap-2" role="alert"><span className="pb-2 text-sm text-slate-600">Clear all?</span><button type="button" onClick={performClear} className="rounded-md bg-rose-700 px-3 py-2 text-sm font-semibold text-white">Confirm</button><button type="button" onClick={() => setConfirming(false)} className="rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold">Cancel</button></div> : null}</div></div></div>
    <div className="space-y-3">{visible.length ? visible.map((record) => <details key={record.id} className="rounded-xl border border-slate-200 bg-white shadow-card"><summary className="cursor-pointer list-none p-5 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-200"><div className="grid gap-3 sm:grid-cols-[155px_minmax(0,1fr)_auto] sm:items-center"><div><p className="text-sm font-semibold text-slate-800">{new Date(record.timestamp).toLocaleString()}</p><p className="mt-1 text-xs text-slate-400">{record.model || "No model response"}</p></div><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-900">{record.request}</p><p className="mt-1 text-xs text-slate-500">{record.tools_used.length ? record.tools_used.map((tool) => toolLabels[tool] || tool).join(", ") : "No tools used"}</p></div><div className="text-right"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${record.status === "success" ? "bg-emerald-50 text-emerald-800" : "bg-rose-50 text-rose-800"}`}>{record.status === "success" ? "Successful" : "Failed"}</span><p className="mt-1 text-xs text-slate-400">{record.tool_calls.length} calls · {duration(record.total_execution_time_ms)}</p></div></div></summary><div className="border-t border-slate-200 p-5"><h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Complete request</h3><p className="mt-2 text-sm leading-6 text-slate-700">{record.request}</p>{record.answer ? <><h3 className="mt-5 text-xs font-semibold uppercase tracking-wider text-slate-500">Assistant response</h3><div className="assistant-markdown mt-2 text-sm leading-6 text-slate-700"><ReactMarkdown remarkPlugins={[remarkGfm]}>{record.answer}</ReactMarkdown></div></> : <p className="mt-4 text-sm text-rose-700">Safe error category: {record.error_category || "Request failed"}</p>}{record.tool_calls.length ? <><h3 className="mt-5 text-xs font-semibold uppercase tracking-wider text-slate-500">Tool calls</h3><div className="mt-2 space-y-2">{record.tool_calls.map((call, index) => <div key={`${call.tool_name}-${index}`} className="flex flex-wrap justify-between gap-3 rounded-lg bg-slate-50 px-4 py-3 text-sm"><span className="font-mono text-xs text-slate-700">{call.tool_name}</span><span className="text-xs text-slate-500">{call.success ? "Completed" : "Failed"} · {duration(call.execution_time_ms)}</span></div>)}</div></> : null}</div></details>) : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><h3 className="font-semibold text-slate-800">No matching history</h3><p className="mt-2 text-sm text-slate-500">Submit an assistant request or adjust the filters.</p></div>}</div>
  </section>;
}
