import { useCallback, useEffect, useMemo, useState } from "react";
import { ChartCard, EmptyState, ErrorState, KpiCard, LoadingState, PageHeader, StatusBadge, integer } from "../components/analytics/DashboardComponents";
import { PlotlyChart } from "../components/analytics/PlotlyChart";
import { InventoryProduct, InventorySummary, ReorderResponse, getInventory, getInventorySummary, getReorderRecommendations } from "../services/api";

type InventoryData = { summary: InventorySummary; products: InventoryProduct[]; reorder: ReorderResponse };

export function InventoryPage() {
  const [data, setData] = useState<InventoryData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [status, setStatus] = useState("All");
  const [category, setCategory] = useState("All");
  const [search, setSearch] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [summary, products, reorder] = await Promise.all([getInventorySummary(), getInventory(), getReorderRecommendations()]); setData({ summary, products, reorder }); } catch { setError("Unable to load inventory analytics from the API."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const categories = useMemo(() => data ? [...new Set(data.products.map((p) => p.category))].sort() : [], [data]);
  const filtered = useMemo(() => data ? data.products.filter((p) => (status === "All" || p.inventory_status === status) && (category === "All" || p.category === category) && (!search.trim() || `${p.product_id} ${p.product_name}`.toLowerCase().includes(search.toLowerCase()))) : [], [data, status, category, search]);
  if (loading) return <LoadingState label="Loading inventory analytics..." />;
  if (error || !data) return <ErrorState message={error || "Inventory data is unavailable."} onRetry={() => void load()} />;

  return <section className="space-y-6">
    <PageHeader eyebrow="Inventory operations" title="Inventory" description="Monitor stock health, supplier exposure, and deterministic restocking priorities across the synthetic catalog." />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><KpiCard label="Total Products" value={integer.format(data.summary.total_products)} /><KpiCard label="Healthy" value={integer.format(data.summary.healthy_products)} /><KpiCard label="Low Stock" value={integer.format(data.summary.low_stock_products)} /><KpiCard label="Critical" value={integer.format(data.summary.critical_products)} /><KpiCard label="Percentage At Risk" value={`${data.summary.percentage_at_risk.toFixed(1)}%`} /><KpiCard label="Units In Stock" value={integer.format(data.summary.total_units_in_stock)} /></div>
    <ChartCard title="Inventory Status Distribution" subtitle="Product counts by deterministic stock threshold."><div className="grid items-center gap-5 lg:grid-cols-[minmax(0,1fr)_280px]"><PlotlyChart height={280} ariaLabel="Inventory status donut chart" data={[{ type: "pie", hole: 0.6, labels: ["Healthy", "Low Stock", "Critical"], values: [data.summary.healthy_products, data.summary.low_stock_products, data.summary.critical_products], marker: { colors: ["#2f855a", "#d69e2e", "#c2415d"] }, textinfo: "label+value", hovertemplate: "%{label}: %{value}<extra></extra>" }]} layout={{ showlegend: false, margin: { l: 20, r: 20, t: 10, b: 10 } }} /><div className="space-y-3">{[["Healthy", data.summary.healthy_products], ["Low Stock", data.summary.low_stock_products], ["Critical", data.summary.critical_products]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between rounded-lg border border-slate-200 px-4 py-3"><StatusBadge status={String(label)} /><span className="font-semibold text-slate-900">{value}</span></div>)}</div></div></ChartCard>

    <ChartCard title="Inventory Detail" subtitle={`${filtered.length} of ${data.products.length} products shown. Filters are applied locally to the 40-product dataset.`}>
      <div className="mb-5 grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold text-slate-600">Search product<input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Name or product ID" className="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-100" /></label><label className="text-xs font-semibold text-slate-600">Status<select value={status} onChange={(e) => setStatus(e.target.value)} className="mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-100"><option>All</option><option>Healthy</option><option>Low Stock</option><option>Critical</option></select></label><label className="text-xs font-semibold text-slate-600">Category<select value={category} onChange={(e) => setCategory(e.target.value)} className="mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-100"><option>All</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label></div>
      {filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3">Product</th><th className="pb-3">Category</th><th className="pb-3 text-right">Stock</th><th className="pb-3 text-right">Reorder</th><th className="pb-3">Status</th><th className="pb-3">Supplier</th><th className="pb-3 text-right">Lead Time</th><th className="pb-3 text-right">Reliability</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((p) => <tr key={p.product_id}><td className="py-3 font-medium text-slate-900">{p.product_name}<span className="ml-2 text-xs text-slate-400">{p.product_id}</span></td><td className="py-3 text-slate-600">{p.category}</td><td className="py-3 text-right">{p.current_stock}</td><td className="py-3 text-right">{p.reorder_level}</td><td className="py-3"><StatusBadge status={p.inventory_status} /></td><td className="py-3 text-slate-600">{p.supplier_name}</td><td className="py-3 text-right">{p.lead_time_days} days</td><td className="py-3 text-right">{(p.reliability_score * 100).toFixed(0)}%</td></tr>)}</tbody></table></div> : <EmptyState message="No products match the current filters." />}
    </ChartCard>

    <ChartCard title="Reorder Priorities" subtitle={`Deterministic business rules using stock, demand, supplier lead time, and reliability. Demand window: ${data.reorder.recent_period_start} to ${data.reorder.recent_period_end}.`}>
      <div className="grid gap-4 lg:grid-cols-2">{data.reorder.recommendations.slice(0, 8).map((item, index) => <article key={item.product_id} className="rounded-lg border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-400">PRIORITY {index + 1} · {item.product_id}</p><h4 className="mt-1 font-semibold text-slate-900">{item.product_name}</h4><p className="mt-1 text-xs text-slate-500">{item.category}</p></div><div className="text-right"><StatusBadge status={item.inventory_status} /><p className="mt-2 text-sm font-semibold text-slate-900">Score {item.priority_score.toFixed(2)}</p></div></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Stock / reorder</dt><dd className="mt-1 font-semibold text-slate-700">{item.current_stock} / {item.reorder_level}</dd></div><div><dt className="text-slate-400">Recent units sold</dt><dd className="mt-1 font-semibold text-slate-700">{item.recent_units_sold}</dd></div><div><dt className="text-slate-400">Supplier</dt><dd className="mt-1 font-semibold text-slate-700">{item.supplier_name}</dd></div><div><dt className="text-slate-400">Lead time / reliability</dt><dd className="mt-1 font-semibold text-slate-700">{item.lead_time_days} days · {(item.reliability_score * 100).toFixed(0)}%</dd></div></dl><p className="mt-4 border-t border-slate-100 pt-3 text-xs leading-5 text-slate-600">{item.recommendation_reason}</p></article>)}</div>
    </ChartCard>
  </section>;
}
